In [20]:
import matplotlib.pyplot as plt
from quantopian.pipeline import Pipeline
from quantopian.research import run_pipeline
from quantopian.research import symbols
from quantopian.research import prices
from quantopian.research import log_prices
from quantopian.research import log_returns
from quantopian.research import volumes
symbol_list_1=[
        'EXC',
        'F',
        'APTV',
        'STZ',
        'EL',
        'SPWR',
        'KO',
        'WMT',
        'HD',
        'NEE',
        'CSX',
        'MCD',
        'SPG',
        'FSLR',
        'NSC'
    ]
symbol_list_2=[
        'HON',
        'GOOG',
        'COP',
        'MRO',
        'C',
        'CRM',
        'QCOM',
        'GILD',
        'AMZN',
        'CVX',
        'FB',
        'MRK',
        'PYPL',
        'AXP',
        'V'
    ]
# plt.figure(0)
Log_returns_1=log_prices(symbol_list_1,start='2004-10-28',end='2004-11-05',frequency='minute').mean(axis=1)
Log_returns_1=Log_returns_1.reindex(index=Log_returns_1.index.tz_convert('US/Eastern'),copy=True)
# Log_returns_1.plot(legend=False)
# Log_returns_2=log_prices(symbol_list_2,start='2004-10-28',end='2004-11-05',frequency='minute').mean(axis=1)
# Log_returns_2=Log_returns_2.reindex(index=Log_returns_1.index.tz_convert('US/Eastern'),copy=True)
# Log_returns_2.plot(legend=False)
# plt.figure(1)
# Log_returns_1=log_prices(symbol_list_1,start='2008-10-30',end='2008-11-07',frequency='minute').mean(axis=1)
# Log_returns_1=Log_returns_1.reindex(index=Log_returns_1.index.tz_convert('US/Eastern'),copy=True)
# Log_returns_1.plot(legend=False)
# Log_returns_2=log_prices(symbol_list_2,start='2008-10-30',end='2008-11-07',frequency='minute').mean(axis=1)
# Log_returns_2=Log_returns_2.reindex(index=Log_returns_1.index.tz_convert('US/Eastern'),copy=True)
# Log_returns_2.plot(legend=False)
# plt.figure(2)
# Log_returns_1=log_prices(symbol_list_1,start='2012-11-01',end='2012-11-09',frequency='minute').mean(axis=1)
# Log_returns_1=Log_returns_1.reindex(index=Log_returns_1.index.tz_convert('US/Eastern'),copy=True)
# Log_returns_1.plot(legend=False)
# Log_returns_2=log_prices(symbol_list_2,start='2012-11-01',end='2012-11-09',frequency='minute').mean(axis=1)
# Log_returns_2=Log_returns_2.reindex(index=Log_returns_1.index.tz_convert('US/Eastern'),copy=True)
# Log_returns_2.plot(legend=False)
# plt.figure(3)
# Log_returns_1=log_prices(symbol_list_1,start='2016-11-3',end='2016-11-11',frequency='minute').mean(axis=1)
# Log_returns_1=Log_returns_1.reindex(index=Log_returns_1.index.tz_convert('US/Eastern'),copy=True)
# Log_returns_1.plot(legend=False)
# Log_returns_2=log_prices(symbol_list_2,start='2016-11-3',end='2016-11-11',frequency='minute').mean(axis=1)
# Log_returns_2=Log_returns_2.reindex(index=Log_returns_1.index.tz_convert('US/Eastern'),copy=True)
# Log_returns_2.plot(legend=False)

In [21]:
def minute_to_intraday(series,f_list):
    """
    series: a pd.Series with datetime index
    f_list: a list of function, each of which with input as pd.series/np.array
    return: a dataframe whose columns are calculated result of f_list
    """
    return series.groupby(series.index.date).agg(f_list)

import numpy as np
def Range(series): return series.max()-series.min()
def first(series): return series[0]
def last(series): return series[-1]
minute_to_intraday(Log_returns_1,[np.mean, Range, np.std, len, first, last])# example for minute_to_intraday

                mean     Range       std    len     first      last
2004-10-28  3.652098  0.010538  0.002445  390.0  3.651332  3.655121
2004-10-29  3.654154  0.004988  0.001011  390.0  3.654730  3.655785
2004-11-01  3.659072  0.009420  0.001637  390.0  3.656525  3.660004
2004-11-02  3.663375  0.008876  0.002387  390.0  3.657859  3.659295
2004-11-03  3.669008  0.011953  0.001695  390.0  3.663143  3.669410
2004-11-04  3.682836  0.023591  0.006770  390.0  3.669050  3.692362
2004-11-05  3.689103  0.007627  0.001683  390.0  3.693094  3.688044

In [22]:
def minute_to_interday(series,f):
    import numpy as np
    def first(series): return series[0]
    def last(series): return series[-1]
    temp=minute_to_intraday(series,[first,last])
    return f(temp['first'],temp['last'].shift(periods=1))

minute_to_interday(Log_returns_1,lambda x,y:x-y)

2004-10-28         NaN
2004-10-29   -0.000391
2004-11-01    0.000741
2004-11-02   -0.002145
2004-11-03    0.003848
2004-11-04   -0.000361
2004-11-05    0.000732
dtype: float64